### PR TITLE
Layout fixes

### PR DESCRIPTION
**Pull request by IgorKhramtsov**
1. After changing device orientation `onboardingStepper` don't rebuilds and appear in wrong position
2. When step overlay should appear on first render of some widget (initState), and this widget is placed on another page, then while switching pages, this widget will be rendered until end of page transition and  `onboardingStepper` will init itself, calc `widgetRect` only on start and render overlay in wrong position.

This pull request fix this two issues.

### CODE REVIEW

**Comment by IgorKhramtsov** [comment]
Yes, I start onboarding on `addPostFrameCallback`, it's appear in wrong position anyway. Because page transition animation takes a few frames to render and if we skip the first one with `addPostFrameCallback`, it doesn't help that much.

**Comment by talamaska** [comment]
Ok, but you don't have context in the initState how do you perform 
```final OnboardingState? onboarding = Onboarding.of(context);```

**Comment by talamaska** [comment]
I explicitly explained in the docs that the onboarding should be defined on top of everything else. nothing is stopping you doing that. The problem you have is because of the way you are trying to use it. Again ignoring the docs and do it you way.
If you want to make a separate PR for the LayoutBuilder it will be great, if not I'll add this fix in the pre-release

**Comment by talamaska** [comment]
On the question why it needs to be on top of everything else, well when you use Provider, do you try to access the provided service/value in the same widget with a key? No, you don't. You declare the Provider, and somewhere down the tree, with a new context, made from another widget or from a Builder, you call Provider.of(context). The only difference is that I don't use Inherited widget.

on the example. What will happen if you put the 
```
 WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
            Onboarding.of(context)!.show();
          });
```
snipped in the MyHomePage in initState?
Why would you call pop and then launch the onboarding?

**Comment by talamaska** [comment]
@IgorKhramtsov btw I don't think you should execute any code before super.initState
```
@override
void initState() {
  isTutorialShown = serviceLocator<Repository>().settings.getTutorialShown(Tutorial.voiceInput);
  super.initState();
}
```

**Pull request closed without merging**
